In [3]:
import pandas as pd

#### Run this notebook first to construct the json file to fill db with it

In [4]:
df = pd.read_csv('./dataset/mozilla_core.csv')
df.head(5)

,Issue_id,Priority,Component,Duplicated_issue,Title,Description,Status,Resolution,Version,Created_time,Resolved_time
0,91,P3,DOM: Core & HTML,NaN,document properties cannot be listed,Created by Till Krech (till@berlin.snafu.de) o...,VERIFIED,FIXED,Trunk,1998-04-07 16:05:23 -0700,2009-02-16 08:04:06 -0800
1,103,P1,Layout: Tables,NaN,layout bug: table cell overflows containing cell,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,FIXED,Trunk,1998-04-07 18:43:26 -0700,2009-02-16 08:05:07 -0800
2,104,P3,Serializers,NaN,table saved as text: missing inter-column space,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,WONTFIX,Trunk,1998-04-07 19:16:02 -0700,2007-04-06 22:26:22 -0700
3,105,P2,Layout: Tables,NaN,nested <TABLE>s: bgcolor of inner table not re...,Created by (msuencks@marcant.de) on Tuesday;...,VERIFIED,FIXED,Trunk,1998-04-07 19:54:41 -0700,2009-02-16 08:18:13 -0800
4,133,P3,Internationalization,NaN,Navigator draws entities like &lt;&amp;&gt; as...,Created by Boris Tobotras (boris@xtalk.msk.su)...,VERIFIED,FIXED,Trunk,1998-04-10 04:41:16 -0700,2009-02-16 08:19:17 -0800

In [5]:
ROWS = 600
df = df.iloc[:1100]
df.head(5)

,Issue_id,Priority,Component,Duplicated_issue,Title,Description,Status,Resolution,Version,Created_time,Resolved_time
0,91,P3,DOM: Core & HTML,NaN,document properties cannot be listed,Created by Till Krech (till@berlin.snafu.de) o...,VERIFIED,FIXED,Trunk,1998-04-07 16:05:23 -0700,2009-02-16 08:04:06 -0800
1,103,P1,Layout: Tables,NaN,layout bug: table cell overflows containing cell,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,FIXED,Trunk,1998-04-07 18:43:26 -0700,2009-02-16 08:05:07 -0800
2,104,P3,Serializers,NaN,table saved as text: missing inter-column space,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,WONTFIX,Trunk,1998-04-07 19:16:02 -0700,2007-04-06 22:26:22 -0700
3,105,P2,Layout: Tables,NaN,nested <TABLE>s: bgcolor of inner table not re...,Created by (msuencks@marcant.de) on Tuesday;...,VERIFIED,FIXED,Trunk,1998-04-07 19:54:41 -0700,2009-02-16 08:18:13 -0800
4,133,P3,Internationalization,NaN,Navigator draws entities like &lt;&amp;&gt; as...,Created by Boris Tobotras (boris@xtalk.msk.su)...,VERIFIED,FIXED,Trunk,1998-04-10 04:41:16 -0700,2009-02-16 08:19:17 -0800

In [6]:
import re
def extract_creator_name(text: str) -> str:
    prefix = "Created by "
    if prefix in text:
        # Get everything after 'Created by '
        after_prefix = text.split(prefix)[1]
        # Split by space and take the first two words (First and Last name)
        parts = after_prefix.split()
        return f"{parts[0]} {parts[1]}"
    return "Author not found"

In [7]:
df["Description"] = df["Description"].fillna("Created by Unknown Author")
df['creator_name'] = df['Description'].apply(extract_creator_name)
df.head(30)

,Issue_id,Priority,Component,Duplicated_issue,Title,Description,Status,Resolution,Version,Created_time,Resolved_time,creator_name
0,91,P3,DOM: Core & HTML,NaN,document properties cannot be listed,Created by Till Krech (till@berlin.snafu.de) o...,VERIFIED,FIXED,Trunk,1998-04-07 16:05:23 -0700,2009-02-16 08:04:06 -0800,Till Krech
1,103,P1,Layout: Tables,NaN,layout bug: table cell overflows containing cell,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,FIXED,Trunk,1998-04-07 18:43:26 -0700,2009-02-16 08:05:07 -0800,Darrell Kindred
2,104,P3,Serializers,NaN,table saved as text: missing inter-column space,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,WONTFIX,Trunk,1998-04-07 19:16:02 -0700,2007-04-06 22:26:22 -0700,Darrell Kindred
3,105,P2,Layout: Tables,NaN,nested <TABLE>s: bgcolor of inner table not re...,Created by (msuencks@marcant.de) on Tuesday;...,VERIFIED,FIXED,Trunk,1998-04-07 19:54:41 -0700,2009-02-16 08:18:13 -0800,(msuencks@marcant.de) on
4,133,P3,Internationalization,NaN,Navigator draws entities like &lt;&amp;&gt; as...,Created by Boris Tobotras (boris@xtalk.msk.su)...,VERIFIED,FIXED,Trunk,1998-04-10 04:41:16 -0700,2009-02-16 08:19:17 -0800,Boris Tobotras
5,134,P2,JavaScript Engine,NaN,Navigator crashes w/ javascript setting textar...,Created by Darrell Kindred (dkindred=mozilla@c...,VERIFIED,WORKSFORME,Trunk,1998-04-10 07:59:33 -0700,2002-01-18 00:39:55 -0800,Darrell Kindred
6,159,P5,JavaScript Engine,NaN,warning fix : ns/js/jsj/jsStubs.c,Created by Rick Osborne (rick@rixsoft.com) on ...,VERIFIED,FIXED,Trunk,1998-04-13 01:23:11 -0700,2009-02-16 08:20:09 -0800,Rick Osborne
7,174,P3,Networking,NaN,URL: mailto:s -> Failed assert on exit at mkge...,Created by Dan McGuirk (mcguirk@indirect.com) ...,VERIFIED,FIXED,Trunk,1998-04-13 10:25:18 -0700,2002-09-01 07:21:08 -0700,Dan McGuirk
8,213,P5,DOM: Core & HTML,NaN,showDocument(javascript:...); broken,Created by Holger Hippenstiel (lynxx@uni.de) o...,VERIFIED,INVALID,Trunk,1998-04-14 14:06:16 -0700,2003-07-21 08:36:19 -0700,Holger Hippenstiel
9,220,P3,Internationalization,NaN,Incorrect display of CP-1250 pages in Unix ver...,Created by Tomas Brodsky (brodsky@cfar.umd.edu...,VERIFIED,FIXED,Trunk,1998-04-14 18:54:25 -0700,1999-04-27 15:12:59 -0700,Tomas Brodsky
10,228,P3,JavaScript Engine,NaN,Navigator spawn a lot of error messages in inf...,Created by Denis Pershin (dyp@inetlab.com) on ...,VERIFIED,FIXED,Trunk,1998-04-15 06:30:38 -0700,2013-10-09 06:49:51 -0700,Denis Pershin
11,247,P3,DOM: Core & HTML,NaN,back button clears hidden fields,Created by lenny karpel (lenny@opentext.com) o...,VERIFIED,WORKSFORME,Trunk,1998-04-16 16:57:02 -0700,1999-08-05 17:03:33 -0700,lenny karpel
12,264,P3,XPCOM,NaN,Fails to complie due to having wrong include,Created by Paul Kanz (pkanz@conix.com) on Wedn...,VERIFIED,WORKSFORME,Trunk,1998-04-22 20:42:24 -0700,1999-07-21 14:43:18 -0700,Paul Kanz
13,273,P4,XUL,24514.0,Submenu open delay wrong on Windows,Created by (shaman@nlc.net.au) on Friday; Ap...,VERIFIED,DUPLICATE,Trunk,1998-04-24 23:07:26 -0700,2000-01-20 18:16:53 -0800,(shaman@nlc.net.au) on
14,279,P3,JavaScript Engine,NaN,Garbage collector incorrectly called during sc...,Created by Andrew Hodgkinson (ahodgkin@acorn.c...,VERIFIED,FIXED,Trunk,1998-04-28 10:40:12 -0700,2003-01-12 18:02:31 -0800,Andrew Hodgkinson
15,289,P3,Networking: Cache,NaN,Cache database changed but files are not (1998...,Created by (tenthumbs@cybernex.net) on Frida...,VERIFIED,WORKSFORME,Trunk,1998-05-01 19:43:40 -0700,2002-06-09 12:57:05 -0700,(tenthumbs@cybernex.net) on
16,300,P3,XPCOM,NaN,CXX V6.0-20 +ANSI requires explicit cast,Created by Berkley Shands (berkley@cs.wustl.ed...,VERIFIED,WORKSFORME,Trunk,1998-05-06 13:32:48 -0700,1999-07-21 14:49:12 -0700,Berkley Shands
17,324,P3,Editor,NaN,explicit casts needed in EditorFrame.cpp,Created by Berkley Shands (berkley@cs.wustl.ed...,VERIFIED,FIXED,Trunk,1998-05-06 18:47:15 -0700,2001-09-12 00:43:03 -0700,Berkley Shands
18,334,P3,Editor,NaN,ANSI disallows enum casts - make explicit in E...,Created by Berkley Shands (berkley@cs.wustl.ed...,VERIFIED,FIXED,Trunk,1998-05-07 18:15:42 -0700,2001-09-12 00:43:03 -0700,Berkley Shands
19,335,P3,Event Handling,NaN,ANSI disallows enum casts - make explicit in H...,Created by Berkley Shands (berkley@cs.wustl.ed...,VERIFIED,FIXED,Trunk,1998-05-07 18:17:21 -0700,1999-04-21 11:23:13 -0700,Berkley Shands
20,346,P2,HTML: Form Submission,NaN,Missing & in parameter; cmd/xfe/forms.c:2116,Created by Ronan Waide (waider@waider.ie) on M...,VERIFIED,FIXED,Trunk,1998-05-11 17:03:09 -0700,1999-04-21 11:23:13 -0700,Ronan Waide
21,387,P3,JavaScript Engine,NaN,warnings when compiling jsmath.c in javascript...,Created by (t92mas@student.tdb.uu.se) on Thu...,VERIFIED,WONTFIX,Trunk,1998-05-21 13:38:11 -0700,2004-07-01 18:02:41 -0700,(t92mas@student.tdb.uu.se) on
22,414,P3,JavaScript Engine,415.0,on resizing browser A HREF= function() js func...,Created by Reba James (rjames@hotoffice.com) o...,VERIFIED,DUPLICATE,Trunk,1998-05-28 19:18:44 -0700,2002-01-18 00:39:55 -0800,Reba James
23,415,P3,JavaScript Engine,NaN,on resizing browser A HREF= function() js func...,Created by Reba James (rjames@hotoffice.com) o...,VERIFIED,INVALID,Trunk,1998-05-28 19:22:52 -0700,2002-01-18 00:39:55 -0800,Reba James
24,420,P3,CSS Parsing and Computation,NaN,[NATIVE-WIDGET] a <select> doesnt show up as t...,Created by brian hourigan (digi@inreach.net) o...,VERIFIED,WONTFIX,Trunk,1998-06-01 00:24:00 -0700,1999-12-21 15:07:39 -0800,brian hourigan
25,432,P3,Plug-ins,NaN,PowerBuilder plugin causes random page fault e...,Created by Jean Campbell (jccampb@mitre.org) o...,VERIFIED,FIXED,Trunk,1998-06-09 18:36:22 -0700,2003-01-12 17:42:28 -0800,Jean Campbell
26,433,P3,Plug-ins,NaN,Page fault error created when Netscape launche...,Created by Jean Campbell (jccampb@mitre.org) o...,VERIFIED,WONTFIX,Trunk,1998-06-09 18:41:42 -0700,1999-04-21 11:23:13 -0700,Jean Campbell
27,434,P3,Plug-ins,432.0,Communicator does not work with PowerBuilder p...,Created by Jean Campbell (jccampb@mitre.org) o...,VERIFIED,DUPLICATE,Trunk,1998-06-09 18:47:20 -0700,1999-04-21 11:23:13 -0700,Jean Campbell
28,436,P3,ImageLib,NaN,Doesnt display some GIFs,Created by (rob@gadgetguru.com) on Tuesday; ...,VERIFIED,FIXED,Trunk,1998-06-09 21:40:25 -0700,1999-04-21 11:23:13 -0700,(rob@gadgetguru.com) on
29,438,P2,Networking: FTP,NaN,Incorrect anonymous FTP login,Created by (chrisputtick@writeme.com) on Wed...,VERIFIED,WONTFIX,Trunk,1998-06-10 19:06:46 -0700,2002-06-09 08:45:56 -0700,(chrisputtick@writeme.com) on

In [8]:
df = df.drop(['Duplicated_issue', 'Issue_id', 'Resolved_time'], axis=1)

In [9]:
df['Component'].unique()

<StringArray>
[           'DOM: Core & HTML',              'Layout: Tables',
                 'Serializers',        'Internationalization',
           'JavaScript Engine',                  'Networking',
                       'XPCOM',                         'XUL',
           'Networking: Cache',                      'Editor',
              'Event Handling',       'HTML: Form Submission',
 'CSS Parsing and Computation',                    'Plug-ins',
                    'ImageLib',             'Networking: FTP',
            'Profile: BackEnd',                      'Layout',
                'HTML: Parser',                         'DOM',
       'Layout: Form Controls',         'Layout: HTML Frames',
                   'Selection',            'Networking: File',
         'Document Navigation',                         'RDF',
                    'Tracking', 'Installer: XPInstall Engine',
              'Security: CAPS',            'Networking: HTTP',
         'Networking: Cookies',             'Embedding: APIs',
                'Layout: Text',    'Layout: Block and Inline']
Length: 34, dtype: str

In [10]:
df['Component'].isna().sum()

np.int64(0)

In [11]:

df['Component'] = df['Component'].replace('Plug-ins', 'Plugins')

In [12]:
import json

# Convert timestamp-like column to datetime if needed
if 'created_time' in df.columns:
    df['Created_time'] = pd.to_datetime(df['Created_time'], errors='coerce')

json_list = []
for _, row in df.iterrows():
    item = {
        'author': row.get('creator_name', ''),
        'created_at': row.get('Created_time').isoformat() if pd.notna(row.get('created_time')) else None,
        'description': row.get('Title', ''),
        'tags': [
            row.get('Version', ''),
            row.get('Priority', ''),
            row.get('Resolution', ''),
        ],
        'module': row.get('Component', ''),
    }
    json_list.append(item)

# Save to JSON file
with open('dataset/mozilla_issues.json', 'w', encoding='utf-8') as f:
    json.dump(json_list, f, ensure_ascii=False, indent=2)

len(json_list)

1100

In [13]:
df.to_csv("../notebook/random_samples.csv")